### PR TITLE
Upgrade rust dependencies and replace failure with anyhow

### PR DESCRIPTION
**Pull request by devashishdxt**

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
Good stuff.

Also happy to replace `anyhow` with something simpler like `thiserror` which seems to be preferred these days. But that is a larger refactor and other PR.

**Comment by ethanfrey** [comment]
No CI tests are running here... I guess I need to test manually before merge

**Comment by devashishdxt** [comment]
This PR also fixes #37.

**Comment by ethanfrey** [comment]
Tested locally, looks good. Thanks.

**Comment by ethanfrey** [comment]
Tagged a v0.6.4 release and pushed a 0.6.4 crate for you to import.

**Pull request merged**
